GET localhost:5000/user/
accept: application/json

###

POST localhost:5000/user
Content-Type: application/json

{
  "login": "Someone",
  "email": "someone@mail.com",
  "password": "ddd"
}

###

POST localhost:5000/user
Content-Type: application/json

{
  "login": "AnotherOne",
  "email": "another.one@mail.pl",
  "password": "eee"
}

###

PUT localhost:5000/user/1
Content-Type: application/json

{
  "login": "DifferentOne"
}

###

GET localhost:5000/user/1
accept: application/json

###

DELETE http://localhost:5000/user/34

