GET localhost:5000/user/
accept: application/json

###

POST localhost:5000/user
Content-Type: application/json

{
  "login": "Damian",
  "email": "gradziuk.damian@o2.pl",
  "password": "ddd"
}

###

POST localhost:5000/user
Content-Type: application/json

{
  "login": "Drugi Damian",
  "email": "damianorr@wp.pl",
  "password": "eee"
}

###

PUT localhost:5000/user/1
Content-Type: application/json

{
  "login": "Gradziuk"
}

###

GET localhost:5000/user/1
accept: application/json

###

DELETE http://localhost:5000/user/34

