GET localhost:5000/user/
accept: application/json

###

POST localhost:5000/user
Content-Type: application/json

{
  "login": "Damian",
  "email": "gradziuk.damian@o2.pl",
  "password": "ddd"
}

###

GET localhost:5000/user/1
accept: application/json
